### ISSUE TITLE
Horizontal scrolling for open tabs

### ISSUE THREAD

**Issue by chefcook** [njust/kubelog#2]
When you open enough tabs and reach the screen limit, you can't scroll left or right to view or close the tabs. Here a horizontal scroll would be very helpful.
![image](https://user-images.githubusercontent.com/12730470/227222616-baf72d94-ee84-44d9-9d79-3d77e7bababa.png)

**Comment by njust** [comment]
Kubelog uses [egui_dock](https://github.com/Adanos020/egui_dock). It seems like they have plans to support a scrolling tab bar in the future: https://github.com/Adanos020/egui_dock/issues/42#issuecomment-1254137887

**Comment by njust** [comment]
Fixed in Version 0.4.0
