### ISSUE TITLE
Colorcode or highlight different env or namespace

### ISSUE THREAD

**Issue by chefcook** [njust/kubelog#9]
is a quality of life upgrade but it would be really helpful if you have logs from different namespaces or environments that you either group them with a colorcoding and or add at the beginning of the tab text field the information from which namespace or environment the logs come from. This should serve the clarity.
![image](https://github.com/njust/kubelog/assets/12730470/a9cf4d49-cbe3-45e6-bf07-0c06d5999b20)

**Comment by njust** [comment]
In the next version, the tabs will have a tooltip with information of the cluster, namespace, pods and containers of the loaded logs.
